#!/bin/bash

set -e
pip3 install -i http://pypi.douban.com/simple --trusted-host pypi.douban.com cffi
pip3 install -i http://pypi.douban.com/simple --trusted-host pypi.douban.com -r /home/work/requirements.txt
##为go设置环境变量
sed -i '/\/usr\/lib\/go-1\.10\/bin/d' /root/.bashrc || echo "failed, but it is ok,don't worry "
source ~/.bashrc
ldconfig


systemctl daemon-reload


systemctl enable daiyi-agentCore.service
systemctl restart daiyi-agentCore.service 
